### ISSUE TITLE
text = tagList() throwing error due to usage of && as of R 4.2.0

### ISSUE THREAD

**Issue by ferguskeatinge** [daattali/shinyalert#78] opened 2023-09-05 17:34 UTC
Hi Dean,

Seems to be a problem with the inclusion of action buttons within a shiny alert when using text = tagList(), if there is more than one action button shiny is now (due to changes in R 4.2.0) throwing a warning followed by an error

"Warning: Error in &&: 'length = 2' in coercion to 'logical(1)'"

i believe it has something to do with this? first seen here (https://stackoverflow.com/a/72848495)

![Untitled_error](https://github.com/daattali/shinyalert/assets/12262076/8118229d-96c9-49e0-973b-629d7c8d7ebc)

not sure if needs addressing

**Comment by daattali** [comment] 2023-09-06 05:10
I think this is a duplicate of https://github.com/daattali/shinyalert/issues/75

It's been fixed in the github version

**Closed by daattali** 2023-09-06 05:10 UTC

**Comment by daattali** [comment] 2024-04-26 23:59
A new version was submitted to CRAN today, it will be on CRAN in a few days
