### ISSUE TITLE
Shinyalert does not display a message

### ISSUE THREAD

**Issue by jberilo** [daattali/shinyalert#27] opened 2020-05-21 18:32 UTC
Good afternoon. I am trying to use the shinyalert package in my application, but it is not displaying anything when it is executed. I believe I am correctly declaring the package and the useShinyalert function. can anybody help me? 
The excerpts follow.

require(shinyalert) # ui.r
require(tidyverse) # server.r
require(plotly) # ui.r
require(writexl) # server.r
source('functions.R')
useShinyalert()
set_wd()
options(shiny.sanitize.errors = FALSE)
options(encoding = "UTF-8")

if (nrow(d()) != 0){

      if(input$date_range[2] >= input$date_range[1] ) {

      #d$Ano_Mes <- paste0(d$ano,"-",sprintf("%02d",d$mes))

      ggplotly(ggplot(data = d() , aes(x=Data, y = Total,group = 
  Referenciamento,color=Referenciamento)) +
                 geom_line( size = 0.5) + geom_point( size = 2)+
                 scale_x_date(date_labels="%d-%m-%Y")+
                 scale_colour_brewer(palette = "Set1")  +
                 labs(y = NULL, x = "Período",title =
                      paste0(input$justif," entre ",as.character(input$date_range[1],"%d-%m-%Y")," e ",as.character(input$date_range[2],"%d-%m-%Y"))))

      } else {

        shinyalert(title = "Datas incorretas!",type="error")

        # showModal(modalDialog(
        #   title = NULL,
        #   "Datas incorretas."))

      }

    } else {

      shinyalert(title = "Não existe informação para este tipo de encaminhamento!",type="error")
      # showModal(modalDialog(
      #   title = NULL,
      #   "Não existe informação para este tipo de encaminhamento.")
      #
      # )

    }

**Comment by daattali** [comment] 2020-05-21 20:05
Hi Jose, if you believe the'res a bug with shinyalert, please post a veyr small reproducible example. The code you submitted is not readable in its current form and has a lot of extra code. Please share a small code sample that includes a full shiny app (in the above code I don't see ui and server definitions for example).

**Comment by jberilo** [comment] 2020-05-23 22:39
Hello Dean.
I cannot say that it is a bug in your package. If I test on a simple application it works. My application is very complex to send you. I am using the shinydashboard package. I don't know if there is incompatibility. I am using R version 3.6.2 and RStudio 1.2.50 with Windows 10. The message simply does not appear when requested. I sent you the lines on which I use the messages.

**Comment by daattali** [comment] 2020-05-23 23:14
shinyalert works with shinydashboard - you can verify this by creating a small shinydashboard app and try using shinyalert inside it. I cannot debug this app for you - you will need to either troubleshoot to find the bug, or at least troubleshoot it enough to get to a point where the issue is still happening but with minimal code. I'm closing this issue since there is'nt anything here that suggests a problem with the package.

If you debug your app and believe that you found a problem with this package and it's not your code, do feel free to open an issue with a specific problem. I'm always happy to fix bugs.

**Closed by daattali** 2020-05-23 23:14 UTC
