### ISSUE TITLE
chaining modals - consecutive modals not displayed when user clicks 'OK' quite fast

### ISSUE THREAD

**Issue by karolinakamuda** [daattali/shinyalert#66] opened 2022-04-21 09:48 UTC
In "Chaining modals" approach, when a button triggering modal is clicked quickly, consecutive modals are not being displayed.
Below a sample of code that can serve as an example.

```
library(shiny)
library(shinyalert)

ui <- fluidPage(
    actionButton("run", "Run")
)

server <- function(input, output, session) {

observeEvent(input$run, {
    shinyalert(
        title = "Do you accept element A?",
        showCancelButton =  TRUE,
        callbackR = function(value) {
            ifelse(value == TRUE,
                   shinyalert(title = "Do you accept element B?",
                              showCancelButton =  TRUE,
                              callbackR = function(value) {
                                  ifelse(value == TRUE, shinyalert(title = "Do you accept element C?",
                                                                   showCancelButton =  TRUE,
                                                                   callbackR = function(value) {
                                                                       ifelse(value == TRUE, shinyalert(title = "Do you accept element D?",
                                             showCancelButton =  TRUE, callbackR = function(value) {
                                                 ifelse(value == TRUE,
                                                        shinyalert(title = "Do you accept element E?",
                                                                   showCancelButton =  TRUE), decision <<- "STOP")}), decision <<- "STOP")}), decision <<- "STOP")}), decision <<- "STOP")}
    )
})
}

shinyApp(ui = ui, server = server)
```

**Comment by daattali** [comment] 2022-04-21 15:56
I believe this is a duplicate of #48 - a known issue (the return value is similar to an input)

**Closed by daattali** 2022-04-21 15:56 UTC
